@extends('layouts.app_home')
@section('css')
 <link href="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.11.4/jquery-ui.css" rel="stylesheet">
@endsection
@section('content')

            <div class="row">
                <div class="col-md-12">
                    <div class="widget">
                        <header class="widget-header">
                            <h4 class="widget-title">Enter DL Information</h4>
                        </header><!-- .widget-header -->
                        <hr class="widget-separator">
                        <div class="widget-body">
                            





                    @if (count($errors) > 0)
                    <div class="alert alert-danger">
                        <ul>
                            @foreach ($errors->all() as $error)
                                <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                    </div>
                @endif

                <div class="alert alert-info">
                  If you dont know the   <strong>DL NUMBER</strong> for the state, leave it blank and it will be autogenerated.
                  If you are editing the state at anytime also edit the <strong>DL NUMBER</strong> accordingly.
                </div>


                    <form method="POST" action="{{ route('store.license') }}">
                        @csrf
                        <div class="form-row">
                            <div class="form-group col-md-4">
                                <label for="inputEmail4">First Name</label>
                                <input type="text" value="{{ old('first_name') }}" name="first_name"
                                    class="form-control" id="inputEmail4">
                            </div>
                            <div class="form-group col-md-4">
                                <label for="inputPassword4">Middle Name (optional)</label>
                                <input type="text" value="{{ old('middle_name') }}" name="middle_name"
                                    class="form-control" >
                            </div>
                            <div class="form-group col-md-4">
                                <label for="inputPassword4">Last Name</label>
                                <input type="text" value="{{ old('last_name') }}" name="last_name"
                                    class="form-control" >
                            </div>
                        </div>

                     <div class="form-row">
                        <div class="form-group col-md-6">
                            <label for="inputEmail4">issued Date <span style="font-size:11px;color:red">(format should be: Year-month-day eg 2021-11-09)</span> </label>
                            <input id="issued_date" type="text" value="{{ old('issued_date') }}" name="issued_date" placeholder="2009-12-02"
                                class="form-control" id="inputEmail4">
                        </div>
                        <div class="form-group col-md-6">
                            <label for="inputPassword4">Date of Birth <span style="font-size:11px;color:red">(format should be: Year-month-day eg 1982-11-09)</span></label>
                            <input id="birth_date" type="text" value="{{ old('birth_date') }}" name="birth_date" placeholder="1980-11-09"
                                class="form-control" >
                        </div>
                    </div>



                    <div class="form-row">
                        <div class="form-group col-md-4">
                            <label for="inputZip">street</label>
                            <input value="{{ old('street') }}" name="street"
                            placeholder="Street (ex. 1023 john Doe Ave)" class="form-control" type="text">
                        </div>
                        <div class="form-group col-md-4">
                            <label for="inputZip">City</label>
                            <input placeholder="City (ex.Cleveland)" value="{{ old('city') }}" name="city" class="form-control"
                                type="text">
                        </div>
                        <div class="form-group col-md-4">
                            <label for="inputCity">State</label>
                            <select name="state"  class="form-control">
                                <option value="">Select</option>
                                <option value="AL">Alabama</option>
                                <option value="AK">Alaska</option>
                                <option value="AZ">Arizona</option>
                                <option value="AR">Arkansas</option>
                                <option value="CA">California</option>
                                {{-- <option value="CO">Colorado</option> --}}
                                <option value="CT">Connecticut</option>
                                <option value="DE">Delaware</option>
                                <option value="FL">Florida</option>
                                <option value="GA_OLD">Georgia Old</option> 
                                <option value="GA">Georgia New</option>
                                <option value="HI">Hawaii</option>
                                <option value="ID">Idaho</option>
                                <option value="IL">Illinois</option>
                                <option value="IN">Indiana</option>
                                <option value="IA">Iowa</option>
                                <option value="KS">Kansas</option>
                                <option value="KY">Kentucky</option>
                                <option value="LA">Louisiana</option>
                                <option value="ME">Maine</option>
                                <option value="MD">Maryland</option>
                                <option value="MA">Massachusetts</option>
                                <option value="MI">Michigan</option>
                                <option value="MN">Minnesota</option>
                                <option value="MS">Mississippi</option>
                                <option value="MO">Missouri</option>
                                <option value="MT">Montana</option>
                                <option value="NC">North Carolina</option>
                                {{-- <option value="ND">North Dakota</option> --}}
                                <option value="NE">Nebraska</option>
                                <option value="NV">Nevada</option>
                                <option value="NH">New Hampshire</option>
                                <option value="NJ">New Jersey</option>
                                <option value="NM">New Mexico</option>
                                {{-- <option value="NY">New York</option> --}}
                                <option value="OH">Ohio</option>
                                <option value="OK">Oklahoma</option>
                                <option value="OR">Oregon</option>
                                <option value="PA">Pennsylvania</option>
                                <option value="RI">Rhode Island</option>
                                <option value="SC">South Carolina</option>
                                <option value="SD">South Dakota</option>
                                <option value="TN">Tennessee</option>
                                <option value="TX">Texas</option>
                                <option value="UT">Utah</option>
                                <option value="VT">Vermont</option>
                                {{-- <option value="VA">Virginia</option> --}}
                                <option value="WA">Washington</option>
                                <option value="WV">West Virginia</option>
                               {{--  <option value="WI">Wisconsin</option>--}}
                                <option value="WY">Wyoming</option> 
                              </select>
                            </select>
                        </div>
                    </div>

                    <div class="form-row">
                        <div class="form-group col-md-4">
                            <label for="inputEmail4">Zip</label>
                            <input  type="number" value="{{ old('zip') }}" name="zip"
                                class="form-control" >
                        </div>
                                
                        <div class="form-group col-md-4">
                            <label for="inputPassword4">Eye Color</label>
                            <select  name="eye_color" class="form-control" >
                                <option value="BLK">Black</option>
                                <option value="BLU">Blue</option>
                                <option value="BRO">Brown</option>
                                <option value="DIC">Dichromatic</option>
                                <option value="GRY">Gray</option>
                                <option value="GRN">Green</option>
                                <option value="HAZ">Hazel</option>
                                <option value="MAR">Maroon</option>
                                <option value="PNK">Pink</option>
                                <option value="UNK">Unknown</option>
                              </select>
                        </div>
                        <div class="form-group col-md-4">
                            <label for="inputPassword4">Hair Color</label>
                                <select  name="hair_color" class="form-control" >
                                    <option value="BAL">Bald</option>
                                    <option value="BLK">Black</option>
                                    <option value="BLN">Blond</option>
                                    <option value="BRO">Brown</option>
                                    <option value="GRY">Gray</option>
                                    <option value="SDY">Sandy</option>
                                    <option value="RED">Red</option>
                                    <option value="UNK">Unknown</option>
                                  </select>
                        </div>
                    </div>

                    <div class="form-row">
                        <div class="form-group col-md-3">
                            <label for="inputPassword4">Gender</label>
                            <select  name="gender" class="form-control" >
                                <option value="M">Male</option>
                                <option value="F">Female</option>
                              </select>
                        </div>
                        <div class="form-group col-md-3">
                            <label for="inputPassword4">Height (Foot)</label>
                            <input id="foot"  min="4" max="7" type="number" value="{{ old('foot') }}" name="foot"
                                class="form-control" >
                        </div>
                                
                        <div class="form-group col-md-3">
                            <label for="inputPassword4">Height (inches)</label>
                            <input  type="number" min="0" max="11" value="{{ old('inches') }}" name="inches"
                                class="form-control" >
                        </div>
                        <div class="form-group col-md-3">
                            <label for="inputPassword4">Weight(lbs)</label>
                            <input  min="50" max="500"  type="number" value="{{ old('weight') }}" name="weight"
                                class="form-control" >
                        </div>
                    </div>

                    <div class="form-row">
                        <div class="form-group col-md-6">
                            <label for="inputPassword4">DL Number</label>
                            <input  type="text" value="{{ old('dl_number') }}" name="dl_number"
                                class="form-control" >
                                <small class="form-text text-muted">* Leave blank if you want auto generated DL number</small>
                        </div>

                        <div class="form-group col-md-6">
                            <label for="inputEmail4">Select side to download</label>
                            <select  name="view" class="form-control" >
                                <option value="front-view">Front View</option>
                                <option value="back-view">Back View</option>
                                <option value="front-and-back-view">Front & Back View</option>
                              </select>
                        </div>
                    </div>

                    <input type="hidden" value="sample.jpg" name="picture">
                    <input type="hidden" value="sample.png" name="background">


                        <button type="submit" class="btn btn-outline-primary">Submit</button>
                    </form>

             




</div><!-- .widget-body -->
</div><!-- .widget -->
</div><!-- END column -->
</div>

<div class="row">
    @include('partials/news')
</div><!-- .row -->


<div class="row">
@include('partials/banner')
</div><!-- .row -->

@endsection







@push('scripts')
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <script type="text/javascript">
        $("#issued_date").datepicker({
            "dateFormat": "yy-mm-dd",
               changeMonth: true,
               changeYear: true,
               showButtonPanel: true,
        });
        $("#expiry_date").datepicker({
            "dateFormat": "yy-mm-dd",
               changeMonth: true,
               changeYear: true,
               showButtonPanel: true,
        });
        $("#birth_date").datepicker({
            "dateFormat": "yy-mm-dd",
               changeMonth: true,
               changeYear: true,
               showButtonPanel: true,           
        });
        
    </script>
@endpush


